# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  docker-base-image:
    docker:
      - image: circleci/node:13.8.0
jobs:
  build:
    executor: docker-base-image
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    executor: docker-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test
  
  analyze:
    executor: docker-base-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  pre-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

